import React, { useState } from 'react';
import { Calendar, CreditCard, Download, Printer, Sparkles, Star, Globe } from 'lucide-react';

const AngelCalculator = () => {
  const [language, setLanguage] = useState('it');
  const [formData, setFormData] = useState({
    nome: '',
    cognome: '',
    email: '',
    cellulare: '',
    prefisso: '+39',
    dataNascita: '',
    accettoPromo: false
  });
  
  const [angelResult, setAngelResult] = useState(null);
  const [selectedPlan, setSelectedPlan] = useState(null);

  const translations = {
    it: {
      title: 'The Angels Calculator',
      subtitle: 'Scopri il Tuo Angelo Custode',
      firstName: 'Nome',
      lastName: 'Cognome',
      email: 'Email',
      phone: 'Cellulare',
      birthDate: 'Data di Nascita',
      promo: 'Autorizzo ad essere contattato/a per offerte promozionali sugli Angeli',
      calculate: 'Calcola il Mio Angelo',
      print: 'Stampa Report',
      newSearch: 'Nuova Ricerca',
      guardianOf: 'Angelo Custode di',
      choir: 'CORO',
      essence: 'ESSENZA',
      freeVersion: 'Versione Gratuita',
      freeText: 'Questo è il tuo Angelo Custode! Per scoprire la preghiera completa e i rituali personalizzati, scegli uno dei piani premium.',
      angelicPrayer: 'Preghiera Angelica',
      prayerInstruction: 'Recita questa preghiera ogni mattina per entrare in sintonia con il tuo Angelo Custode.',
      angelicQualities: 'Qualità Angeliche',
      quality1: 'Protezione spirituale costante',
      quality2: 'Guida nelle decisioni importanti',
      quality3: 'Supporto nei momenti difficili',
      quality4: 'Sviluppo essenza',
      personalRituals: 'Rituali Personalizzati',
      activation: 'ATTIVAZIONE ANGELO CUSTODE',
      activationText: 'Riceverai attivazione energetica del tuo Angelo',
      activationNote: 'Questa attivazione apre un canale diretto con il tuo Angelo Custode',
      services: 'Scopri i Nostri Servizi Angelici!',
      free: 'GRATIS',
      active: 'Attivo',
      select: 'Seleziona',
      buy: 'Acquista',
      howItWorks: 'Come Funziona',
      step1: 'Scegli il tuo piano',
      step2: 'Pagamento sicuro PayPal',
      step3: 'Ricevi report via email',
      fillRequired: 'Compila tutti i campi obbligatori'
    },
    en: {
      title: 'The Angels Calculator',
      subtitle: 'Discover Your Guardian Angel',
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email',
      phone: 'Phone',
      birthDate: 'Birth Date',
      promo: 'I authorize to be contacted for promotional offers about Angels',
      calculate: 'Calculate My Angel',
      print: 'Print Report',
      newSearch: 'New Search',
      guardianOf: 'Guardian Angel of',
      choir: 'CHOIR',
      essence: 'ESSENCE',
      freeVersion: 'Free Version',
      freeText: 'This is your Guardian Angel! To discover the complete prayer and personalized rituals, choose one of the premium plans.',
      angelicPrayer: 'Angelic Prayer',
      prayerInstruction: 'Recite this prayer every morning to attune with your Guardian Angel.',
      angelicQualities: 'Angelic Qualities',
      quality1: 'Constant spiritual protection',
      quality2: 'Guidance in important decisions',
      quality3: 'Support in difficult times',
      quality4: 'Essence development',
      personalRituals: 'Personalized Rituals',
      activation: 'GUARDIAN ANGEL ACTIVATION',
      activationText: 'You will receive energetic activation of your Angel',
      activationNote: 'This activation opens a direct channel with your Guardian Angel',
      services: 'Discover Our Angelic Services!',
      free: 'FREE',
      active: 'Active',
      select: 'Select',
      buy: 'Buy',
      howItWorks: 'How It Works',
      step1: 'Choose your plan',
      step2: 'Secure PayPal payment',
      step3: 'Receive report via email',
      fillRequired: 'Fill in all required fields'
    },
    fr: {
      title: 'The Angels Calculator',
      subtitle: 'Découvrez Votre Ange Gardien',
      firstName: 'Prénom',
      lastName: 'Nom',
      email: 'Email',
      phone: 'Téléphone',
      birthDate: 'Date de Naissance',
      promo: 'J\'autorise à être contacté(e) pour des offres promotionnelles sur les Anges',
      calculate: 'Calculer Mon Ange',
      print: 'Imprimer Rapport',
      newSearch: 'Nouvelle Recherche',
      guardianOf: 'Ange Gardien de',
      choir: 'CHOEUR',
      essence: 'ESSENCE',
      freeVersion: 'Version Gratuite',
      freeText: 'Ceci est votre Ange Gardien! Pour découvrir la prière complète et les rituels personnalisés, choisissez un des plans premium.',
      angelicPrayer: 'Prière Angélique',
      prayerInstruction: 'Récitez cette prière chaque matin pour vous harmoniser avec votre Ange Gardien.',
      angelicQualities: 'Qualités Angéliques',
      quality1: 'Protection spirituelle constante',
      quality2: 'Guidance dans les décisions importantes',
      quality3: 'Soutien dans les moments difficiles',
      quality4: 'Développement essence',
      personalRituals: 'Rituels Personnalisés',
      activation: 'ACTIVATION ANGE GARDIEN',
      activationText: 'Vous recevrez l\'activation énergétique de votre Ange',
      activationNote: 'Cette activation ouvre un canal direct avec votre Ange Gardien',
      services: 'Découvrez Nos Services Angéliques!',
      free: 'GRATUIT',
      active: 'Actif',
      select: 'Sélectionner',
      buy: 'Acheter',
      howItWorks: 'Comment Ça Marche',
      step1: 'Choisissez votre plan',
      step2: 'Paiement sécurisé PayPal',
      step3: 'Recevez rapport par email',
      fillRequired: 'Remplir tous les champs obligatoires'
    },
    es: {
      title: 'The Angels Calculator',
      subtitle: 'Descubre Tu Ángel Guardián',
      firstName: 'Nombre',
      lastName: 'Apellido',
      email: 'Email',
      phone: 'Teléfono',
      birthDate: 'Fecha de Nacimiento',
      promo: 'Autorizo a ser contactado/a para ofertas promocionales sobre Ángeles',
      calculate: 'Calcular Mi Ángel',
      print: 'Imprimir Informe',
      newSearch: 'Nueva Búsqueda',
      guardianOf: 'Ángel Guardián de',
      choir: 'CORO',
      essence: 'ESENCIA',
      freeVersion: 'Versión Gratuita',
      freeText: '¡Este es tu Ángel Guardián! Para descubrir la oración completa y los rituales personalizados, elige uno de los planes premium.',
      angelicPrayer: 'Oración Angélica',
      prayerInstruction: 'Recita esta oración cada mañana para sintonizar con tu Ángel Guardián.',
      angelicQualities: 'Cualidades Angélicas',
      quality1: 'Protección espiritual constante',
      quality2: 'Guía en decisiones importantes',
      quality3: 'Apoyo en momentos difíciles',
      quality4: 'Desarrollo esencia',
      personalRituals: 'Rituales Personalizados',
      activation: 'ACTIVACIÓN ÁNGEL GUARDIÁN',
      activationText: 'Recibirás activación energética de tu Ángel',
      activationNote: 'Esta activación abre un canal directo con tu Ángel Guardián',
      services: '¡Descubre Nuestros Servicios Angélicos!',
      free: 'GRATIS',
      active: 'Activo',
      select: 'Seleccionar',
      buy: 'Comprar',
      howItWorks: 'Cómo Funciona',
      step1: 'Elige tu plan',
      step2: 'Pago seguro PayPal',
      step3: 'Recibe informe por email',
      fillRequired: 'Completa todos los campos obligatorios'
    },
    de: {
      title: 'The Angels Calculator',
      subtitle: 'Entdecke Deinen Schutzengel',
      firstName: 'Vorname',
      lastName: 'Nachname',
      email: 'Email',
      phone: 'Telefon',
      birthDate: 'Geburtsdatum',
      promo: 'Ich erlaube, für Werbeangebote über Engel kontaktiert zu werden',
      calculate: 'Berechne Meinen Engel',
      print: 'Bericht Drucken',
      newSearch: 'Neue Suche',
      guardianOf: 'Schutzengel von',
      choir: 'CHOR',
      essence: 'ESSENZ',
      freeVersion: 'Kostenlose Version',
      freeText: 'Dies ist dein Schutzengel! Um das vollständige Gebet und personalisierte Rituale zu entdecken, wähle einen der Premium-Pläne.',
      angelicPrayer: 'Engelgebet',
      prayerInstruction: 'Rezitiere dieses Gebet jeden Morgen, um dich mit deinem Schutzengel zu verbinden.',
      angelicQualities: 'Engelhafte Qualitäten',
      quality1: 'Ständiger spiritueller Schutz',
      quality2: 'Führung bei wichtigen Entscheidungen',
      quality3: 'Unterstützung in schwierigen Zeiten',
      quality4: 'Essenzentwicklung',
      personalRituals: 'Personalisierte Rituale',
      activation: 'SCHUTZENGEL AKTIVIERUNG',
      activationText: 'Du erhältst die energetische Aktivierung deines Engels',
      activationNote: 'Diese Aktivierung öffnet einen direkten Kanal zu deinem Schutzengel',
      services: 'Entdecke Unsere Engeldienste!',
      free: 'KOSTENLOS',
      active: 'Aktiv',
      select: 'Wählen',
      buy: 'Kaufen',
      howItWorks: 'Wie Es Funktioniert',
      step1: 'Wähle deinen Plan',
      step2: 'Sichere PayPal-Zahlung',
      step3: 'Erhalte Bericht per Email',
      fillRequired: 'Fülle alle Pflichtfelder aus'
    }
  };

  const t = translations[language];

  const languages = [
    { code: 'it', flag: '🇮🇹', name: 'Italiano' },
    { code: 'en', flag: '🇺🇸', name: 'English' },
    { code: 'fr', flag: '🇫🇷', name: 'Français' },
    { code: 'es', flag: '🇪🇸', name: 'Español' },
    { code: 'de', flag: '🇩🇪', name: 'Deutsch' }
  ];

  const prefissi = [
    { code: '+39', flag: '🇮🇹' },
    { code: '+1', flag: '🇺🇸' },
    { code: '+44', flag: '🇬🇧' },
    { code: '+33', flag: '🇫🇷' },
    { code: '+34', flag: '🇪🇸' },
    { code: '+49', flag: '🇩🇪' }
  ];

  const angelsDB = [
    { num: 1, nome: 'VEHUIAH', coro: 'SERAFINI', essenza: 'VOLONTA', inizio: '03-21', fine: '03-25', preghiera: 'Dio elevato e esaltato sopra tutte le cose' },
    { num: 2, nome: 'JELIEL', coro: 'SERAFINI', essenza: 'AMORE E SAGGEZZA', inizio: '03-26', fine: '03-30', preghiera: 'Dio soccorrevole' },
    { num: 3, nome: 'SITAEL', coro: 'SERAFINI', essenza: 'COSTRUTTORE', inizio: '03-31', fine: '04-04', preghiera: 'Dio speranza di tutte le creature' },
    { num: 4, nome: 'ELEMIAH', coro: 'SERAFINI', essenza: 'POTERE DIVINO', inizio: '04-05', fine: '04-09', preghiera: 'Dio nascosto' },
    { num: 5, nome: 'MAHASIAH', coro: 'SERAFINI', essenza: 'RETTIFICATORE', inizio: '04-10', fine: '04-14', preghiera: 'Dio salvatore' },
    { num: 6, nome: 'LELAHEL', coro: 'SERAFINI', essenza: 'LUCE DELL AMORE', inizio: '04-15', fine: '04-20', preghiera: 'Dio lodevole' },
    { num: 7, nome: 'ACHAIAH', coro: 'SERAFINI', essenza: 'PAZIENZA', inizio: '04-21', fine: '04-25', preghiera: 'Dio buono e paziente' },
    { num: 8, nome: 'CAHETEL', coro: 'SERAFINI', essenza: 'BENEDIZIONE', inizio: '04-26', fine: '04-30', preghiera: 'Dio adorabile' },
    { num: 9, nome: 'HAZIEL', coro: 'CHERUBINI', essenza: 'MISERICORDIA', inizio: '05-01', fine: '05-05', preghiera: 'Dio misericordioso' },
    { num: 10, nome: 'ALADIAH', coro: 'CHERUBINI', essenza: 'GRAZIA DIVINA', inizio: '05-06', fine: '05-10', preghiera: 'Dio propizio' },
    { num: 11, nome: 'LAUVIAH', coro: 'CHERUBINI', essenza: 'VITTORIA', inizio: '05-11', fine: '05-15', preghiera: 'Dio lodato ed esaltato' },
    { num: 12, nome: 'HAHAIAH', coro: 'CHERUBINI', essenza: 'RIFUGIO', inizio: '05-16', fine: '05-20', preghiera: 'Dio rifugio' },
    { num: 13, nome: 'YEZALEL', coro: 'CHERUBINI', essenza: 'FEDELTA', inizio: '05-21', fine: '05-25', preghiera: 'Dio glorificato' },
    { num: 14, nome: 'MEBAHEL', coro: 'CHERUBINI', essenza: 'VERITA E LIBERTA', inizio: '05-26', fine: '05-31', preghiera: 'Dio conservatore' },
    { num: 15, nome: 'HARIEL', coro: 'CHERUBINI', essenza: 'PURIFICAZIONE', inizio: '06-01', fine: '06-05', preghiera: 'Dio creatore' },
    { num: 16, nome: 'HAKAMIAH', coro: 'CHERUBINI', essenza: 'LEALTA', inizio: '06-06', fine: '06-10', preghiera: 'Dio che erige l universo' },
    { num: 17, nome: 'LAUVIAH', coro: 'TRONI', essenza: 'RIVELAZIONE', inizio: '06-11', fine: '06-15', preghiera: 'Dio ammirevole' },
    { num: 18, nome: 'CALIEL', coro: 'TRONI', essenza: 'GIUSTIZIA', inizio: '06-16', fine: '06-21', preghiera: 'Dio pronto a soccorrere' },
    { num: 19, nome: 'LEUVIAH', coro: 'TRONI', essenza: 'INTELLIGENZA', inizio: '06-22', fine: '06-26', preghiera: 'Dio che accoglie i peccatori' },
    { num: 20, nome: 'PAHALIAH', coro: 'TRONI', essenza: 'REDENZIONE', inizio: '06-27', fine: '07-01', preghiera: 'Dio redentore' },
    { num: 21, nome: 'NELCHAEL', coro: 'TRONI', essenza: 'SAPIENZA', inizio: '07-02', fine: '07-06', preghiera: 'Dio solo e unico' },
    { num: 22, nome: 'YEIAYEL', coro: 'TRONI', essenza: 'FORTUNA', inizio: '07-07', fine: '07-11', preghiera: 'Dio che ascolta' },
    { num: 23, nome: 'MELAHEL', coro: 'TRONI', essenza: 'GUARIGIONE', inizio: '07-12', fine: '07-16', preghiera: 'Dio che libera dal male' },
    { num: 24, nome: 'HAHEUIAH', coro: 'TRONI', essenza: 'PROTEZIONE', inizio: '07-17', fine: '07-22', preghiera: 'Dio buono' },
    { num: 25, nome: 'NITH-HAIAH', coro: 'DOMINAZIONI', essenza: 'SAGGEZZA', inizio: '07-23', fine: '07-27', preghiera: 'Dio che dona saggezza' },
    { num: 26, nome: 'HAAIAH', coro: 'DOMINAZIONI', essenza: 'ORDINE', inizio: '07-28', fine: '08-01', preghiera: 'Dio nascosto' },
    { num: 27, nome: 'YERATEL', coro: 'DOMINAZIONI', essenza: 'CIVILIZZAZIONE', inizio: '08-02', fine: '08-06', preghiera: 'Dio che punisce i malvagi' },
    { num: 28, nome: 'SEHEIAH', coro: 'DOMINAZIONI', essenza: 'LONGEVITA', inizio: '08-07', fine: '08-12', preghiera: 'Dio che guarisce' },
    { num: 29, nome: 'REIYEL', coro: 'DOMINAZIONI', essenza: 'LIBERAZIONE', inizio: '08-13', fine: '08-17', preghiera: 'Dio pronto a soccorrere' },
    { num: 30, nome: 'OMAEL', coro: 'DOMINAZIONI', essenza: 'MOLTIPLICAZIONE', inizio: '08-18', fine: '08-22', preghiera: 'Dio paziente' },
    { num: 31, nome: 'LECABEL', coro: 'DOMINAZIONI', essenza: 'TALENTO', inizio: '08-23', fine: '08-28', preghiera: 'Dio che ispira' },
    { num: 32, nome: 'VASARIAH', coro: 'DOMINAZIONI', essenza: 'GIUSTIZIA', inizio: '08-29', fine: '09-02', preghiera: 'Dio giusto' },
    { num: 33, nome: 'YEHUIAH', coro: 'POTESTA', essenza: 'CONOSCENZA', inizio: '09-03', fine: '09-07', preghiera: 'Dio onnisciente' },
    { num: 34, nome: 'LEHAHIAH', coro: 'POTESTA', essenza: 'OBBEDIENZA', inizio: '09-08', fine: '09-12', preghiera: 'Dio clemente' },
    { num: 35, nome: 'CHAVAKHIAH', coro: 'POTESTA', essenza: 'RICONCILIAZIONE', inizio: '09-13', fine: '09-17', preghiera: 'Dio che dona gioia' },
    { num: 36, nome: 'MENADEL', coro: 'POTESTA', essenza: 'LAVORO', inizio: '09-18', fine: '09-23', preghiera: 'Dio adorabile' },
    { num: 37, nome: 'ANIEL', coro: 'POTESTA', essenza: 'CORAGGIO', inizio: '09-24', fine: '09-28', preghiera: 'Dio delle virtu' },
    { num: 38, nome: 'HAAMIAH', coro: 'POTESTA', essenza: 'RITUALE', inizio: '09-29', fine: '10-03', preghiera: 'Dio speranza' },
    { num: 39, nome: 'REHAEL', coro: 'POTESTA', essenza: 'RISPETTO', inizio: '10-04', fine: '10-08', preghiera: 'Dio che accoglie' },
    { num: 40, nome: 'YEIAZEL', coro: 'POTESTA', essenza: 'CONSOLAZIONE', inizio: '10-09', fine: '10-13', preghiera: 'Dio che rallegra' },
    { num: 41, nome: 'HAHAHEL', coro: 'VIRTU', essenza: 'MISSIONE', inizio: '10-14', fine: '10-18', preghiera: 'Dio in tre persone' },
    { num: 42, nome: 'MIKAEL', coro: 'VIRTU', essenza: 'ORDINE POLITICO', inizio: '10-19', fine: '10-23', preghiera: 'Dio simile a Dio' },
    { num: 43, nome: 'VEULIAH', coro: 'VIRTU', essenza: 'PROSPERITA', inizio: '10-24', fine: '10-28', preghiera: 'Dio re dominatore' },
    { num: 44, nome: 'YELAHIAH', coro: 'VIRTU', essenza: 'KARMA', inizio: '10-29', fine: '11-02', preghiera: 'Dio eterno' },
    { num: 45, nome: 'SEALIAH', coro: 'VIRTU', essenza: 'MOTIVAZIONE', inizio: '11-03', fine: '11-07', preghiera: 'Dio motore' },
    { num: 46, nome: 'ARIEL', coro: 'VIRTU', essenza: 'PERCEZIONE', inizio: '11-08', fine: '11-12', preghiera: 'Dio rivelatore' },
    { num: 47, nome: 'ASALIAH', coro: 'VIRTU', essenza: 'CONTEMPLAZIONE', inizio: '11-13', fine: '11-17', preghiera: 'Dio giusto' },
    { num: 48, nome: 'MIHAEL', coro: 'VIRTU', essenza: 'FECONDITA', inizio: '11-18', fine: '11-22', preghiera: 'Dio padre soccorrevole' },
    { num: 49, nome: 'VEHUEL', coro: 'PRINCIPATI', essenza: 'ELEVAZIONE', inizio: '11-23', fine: '11-27', preghiera: 'Dio grande e elevato' },
    { num: 50, nome: 'DANIEL', coro: 'PRINCIPATI', essenza: 'ELOQUENZA', inizio: '11-28', fine: '12-02', preghiera: 'Dio segno di misericordia' },
    { num: 51, nome: 'HAHASIAH', coro: 'PRINCIPATI', essenza: 'MEDICINA UNIVERSALE', inizio: '12-03', fine: '12-07', preghiera: 'Dio nascosto' },
    { num: 52, nome: 'IMAMIAH', coro: 'PRINCIPATI', essenza: 'ESPIAZIONE', inizio: '12-08', fine: '12-12', preghiera: 'Dio elevato' },
    { num: 53, nome: 'NANAEL', coro: 'PRINCIPATI', essenza: 'COMUNICAZIONE', inizio: '12-13', fine: '12-16', preghiera: 'Dio che abbassa i superbi' },
    { num: 54, nome: 'NITHAEL', coro: 'PRINCIPATI', essenza: 'GIOVINEZZA ETERNA', inizio: '12-17', fine: '12-21', preghiera: 'Re dei cieli' },
    { num: 55, nome: 'MEBAHIAH', coro: 'PRINCIPATI', essenza: 'LUCIDITA', inizio: '12-22', fine: '12-26', preghiera: 'Dio eterno' },
    { num: 56, nome: 'POYEL', coro: 'PRINCIPATI', essenza: 'FORTUNA', inizio: '12-27', fine: '12-31', preghiera: 'Dio che sostiene' },
    { num: 57, nome: 'NEMAMIAH', coro: 'ARCANGELI', essenza: 'DISCERNIMENTO', inizio: '01-01', fine: '01-05', preghiera: 'Dio lodevole' },
    { num: 58, nome: 'YEIALEL', coro: 'ARCANGELI', essenza: 'FORZA MENTALE', inizio: '01-06', fine: '01-10', preghiera: 'Dio che esaudisce' },
    { num: 59, nome: 'HARAEL', coro: 'ARCANGELI', essenza: 'RICCHEZZA', inizio: '01-11', fine: '01-15', preghiera: 'Dio che conosce tutto' },
    { num: 60, nome: 'MITZRAEL', coro: 'ARCANGELI', essenza: 'RIPARAZIONE', inizio: '01-16', fine: '01-20', preghiera: 'Dio che solleva' },
    { num: 61, nome: 'UMABEL', coro: 'ARCANGELI', essenza: 'AFFINITA', inizio: '01-21', fine: '01-25', preghiera: 'Dio immenso' },
    { num: 62, nome: 'IAH-HEL', coro: 'ARCANGELI', essenza: 'DESIDERIO DI SAPERE', inizio: '01-26', fine: '01-30', preghiera: 'Dio supremo' },
    { num: 63, nome: 'ANAUEL', coro: 'ARCANGELI', essenza: 'PERCEZIONE UNITA', inizio: '01-31', fine: '02-04', preghiera: 'Dio infinitamente buono' },
    { num: 64, nome: 'MEHIEL', coro: 'ARCANGELI', essenza: 'VIVIFICAZIONE', inizio: '02-05', fine: '02-09', preghiera: 'Dio che vivifica' },
    { num: 65, nome: 'DAMABIAH', coro: 'ANGELI', essenza: 'FONTE DI SAGGEZZA', inizio: '02-10', fine: '02-14', preghiera: 'Dio fonte di saggezza' },
    { num: 66, nome: 'MANAKEL', coro: 'ANGELI', essenza: 'CONOSCENZA', inizio: '02-15', fine: '02-19', preghiera: 'Dio che tutto conosce' },
    { num: 67, nome: 'EYAEL', coro: 'ANGELI', essenza: 'TRASFORMAZIONE', inizio: '02-20', fine: '02-24', preghiera: 'Dio delizia' },
    { num: 68, nome: 'HABUHIAH', coro: 'ANGELI', essenza: 'GUARIGIONE', inizio: '02-25', fine: '02-29', preghiera: 'Dio che dona generosamente' },
    { num: 69, nome: 'ROCHEL', coro: 'ANGELI', essenza: 'RESTITUZIONE', inizio: '03-01', fine: '03-05', preghiera: 'Dio che vede tutto' },
    { num: 70, nome: 'JABAMIAH', coro: 'ANGELI', essenza: 'ALCHIMIA', inizio: '03-06', fine: '03-10', preghiera: 'Verbo che produce tutto' },
    { num: 71, nome: 'HAIAIEL', coro: 'ANGELI', essenza: 'ARMI', inizio: '03-11', fine: '03-15', preghiera: 'Dio padrone universo' },
    { num: 72,
